lst = ["a"]
random_nos = 0  # no. of random numbers generated by module


def random():
    global lst, random_nos
    if len(lst) > 200:
        lst = ["a"]
    lst.append(lst[-1] + "e")
    seed = str(id(lst[-1]))
    # print("address->", seed)  # for debugging purpose
    sum = 0
    for i in seed:
        sum += int(i)

    # print("sum->", sum)  # for debugging purpose

    exp = int(seed[-2])
    num = sum * exp
    num = str(num)
    # print(f"sum after multiplication with {seed[-2]} ->", num)  # for debugging purpose
    num = int(num[-1])

    return num
